### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by collegeimprovements** [smith-carson/ember-pdf-js#5]
How can I use this? Is there any component for it? And are you planning to continuing your work on this project?

**Comment by leojpod** [comment]
Hi there!

Yes, the development should carry on and yes there are 2 components: one to render a given PDF and one to control it (toolbar). 

You can have a quick look at how to do the basics in the dummy app ([here](https://github.com/smith-carson/ember-pdf-js/blob/master/tests/dummy/app/templates/application.hbs)).

In most cases, you will want to extend the toolbar component to have you own layout / html / css ... 
I should put an example of that in the README soon. 

In the meantime I can explain you how to deal with it if you need it right now :)

**Comment by collegeimprovements** [comment]
Thank you @leojpod  :) I'm trying it now....will ask question if get stuck if you don't mind :)

**Comment by leojpod** [comment]
Sure!

**Comment by DarrenDrumm** [comment]
Hi, 

I was just wondering can I pass in a binary value from a model in order to view the pdf? pdf.js does allow this but I was wondering if your addon allows this?

There also appears to be an issue as it installs via npm but the source then looks for pdfjs-dist in the bower_components directory which it does not as it's in node_modules.

I performed a bower install and managed to get the view to display albeit without a pdf loaded.

Also, when in development which directory should the actual pdf document be in so that it loads if given a file name.

**Comment by leojpod** [comment]
@collegeimprovements I've added some explanation in the readme. 

@DarrenDrumm sorry for the time it took to answer but you should be able to put your pdf file in the public folder of your ember app. Regarding the binary value, I haven't tried it. Do you know which param is used by pdf.js to do that? 
Right now, the addon use `pdfjs.getDocument(uri)` where `uri` is the value passed to `pdf` to the viewer component. 
I think some of my college dealt with the bower_components issue, can you still reproduce it?
